#### General information about the project    ####
#### All this will be visible on DataCamp.com ####
title          : "Dr. Semmelweis and the Discovery of Handwashing"
description    : >
  Reanalyse the data behind one of the most important discoveries of modern medicine: handwashing.
long_description: |
  In 1847, the Hungarian physician Ignaz Semmelweis made a breakthough discovery:
  he discovers handwashing. Contaminated hands was a major cause of childbed fever
  and by enforcing handwashing at his hospital he saved hundreds of lives. 
  
  In this R project we will reanalyze the medical data Semmelweis collected.
  This project assumes you can manipulate data frames using `dplyr` and make
  simple plots using `ggplot2`. You can learn these skills in the course 
  [Introduction to the Tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse).
  
#### Metadata regarding course requirements and topics ####
#### This will be updated by your DataCamp contact     ####
technology: 1 # 1 == R, 2 == python, 3 == sql # Automatically set
# IDs for courses that are prerequisites
#  see https://mb.datacamp.com/question/126 for IDs
prerequisites: # DataCamp fills out
  - 4914 # Introduction to the Tidyverse
difficulty_level: 2 # 1 == easy, 2 == medium, 3 == hard # DataCamp fills outs
# IDs for the topics the project covers
# See here for topic IDs: http://bit.ly/project-topic-ids
topics: # DataCamp fills out
  - 3
  - 4
  - 12
#### Technical settings for the docker image running the project ####
#### This will be updated by your DataCamp contact.              ####
language       : r # One of r, python or sql
# The name of the docker image used to run the course
from           : 'r-notebooks-prod:v2.0.0'
runtime_config : default # default/heavy . Set to heavy for more resource intensive projects.